### ISSUE TITLE
Archiving this repo

### ISSUE THREAD

**Issue by homura** [xxuejie/ckb-js-toolkit#22]
This repo is no longer maintained, it was moved to lumos as a [sub package][lumos-toolkit], and since the features in this package have more intersection with lumos, such as `Collector`, `RPC`, etc., we strongly recommend that you use lumos instead of ckb-js-toolkit

## Codecs

The [`ckb-lumos/codec`][lumos-codec] helps you serialize and normalize in one function instead of split them, it is easier to understand and usage

```ts
import { blockchain } from '@ckb-lumos/base'

const packed: Uint8Array = blockchain.Script.pack({ 
  hashType: 'type', 
  args: '0x', 
  codeHash: '0x0000000000000000000000000000000000000000000000000000000000000000',
});

// blockchain.Script.unpack(packed)

```

## Collector

The [`ckb-lumos/ckb-indexer`][lumos-indexer] provides the same feature and very similar APIs for collecting cells from CKB Indexer or CKB

```ts
import { Indexer } from '@ckb-lumos/ckb-indexer';

const indexer = new Indexer('http://localhost:8114');

async function calcTotalCapacity(lock: Script): Promise<BI> {
  const collector = indexer.collector({ lock });

  let balance: BI = BI.from(0);
  for await (const cell of collector.collect()) {
    balance = balance.add(cell.cellOutput.capacity);
  }

  return balance;
}

calcTotalCapacity(aliceSecp256k1Lock).then(console.log)

```

## RPC

Check out [`@ckb-lumos/rpc`][lumos-rpc], it is more type-friendly for the modern editor(IDE)

[lumos-codec]: https://github.com/ckb-js/lumos/tree/develop/packages/codec "@ckb-lumos/codec"
[lumos-toolkit]: https://github.com/ckb-js/lumos/tree/develop/packages/toolkit "@ckb-lumos/toolkit"
[lumos-rpc]: https://github.com/ckb-js/lumos/tree/develop/packages/rpc "@ckb-lumos/rpc"
[lumos-indexer]: https://github.com/ckb-js/lumos/tree/develop/packages/ckb-indexer "@ckb-lumos/indexer"

**Comment by xxuejie** [comment]
I will personally continue to maintain this project. It's indeed true that lumos (and possibly ccc) provides the same personality. However, the Nervos ecosystem is full of different likes and preferences. The toolkit here provides a different perspective compared to lumos and ccc. So while it's unlikely major features are added here, I will continue to work on this when problems arise. And of course, I'm happy moving this from nervos organization back to a personal project if we see fit.
